#ifndef ENUMS_H
#define ENUMS_H

enum TType {INTEGER, BOOLEAN, NONE};
enum TTag {PROGRAM, DECL_BLOCK, DECL, VAR_DECL, CONST_DECL, STMT_BLOCK, ASSIGNMENT_OP, RETURN, EXPR_OP, CONST_VALUE, NONE};
enum TBoolean {TRUE, FALSE};
enum TOperator {PLUS, MINUS, MULTIPLY, DIVIDE, ASSIGN};

#endif